# Generated by Django 2.1.1 on 2018-10-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datacadastro', models.DateField(verbose_name='datacadastro')),
            ],
            options={
                'db_table': 'aluno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlunoFrequenciaMes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalfaltas', models.IntegerField()),
            ],
            options={
                'db_table': 'alunofrequenciames',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusmatricula', models.CharField(max_length=255)),
                ('datamatricula', models.DateField()),
                ('statusatual', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'matricula',
                'managed': False,
            },
        ),
    ]
