# Generated by Django 2.1.2 on 2018-11-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('perfilexterno', models.BooleanField()),
                ('vertodasasescolas', models.BooleanField()),
            ],
            options={
                'db_table': 'perfil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=255, null=True, verbose_name='cpf')),
                ('datanascimento', models.DateField(verbose_name='datanascimento')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('rg', models.CharField(max_length=255, null=True, verbose_name='rg')),
                ('nacionalidade', models.CharField(max_length=255, verbose_name='nacionalidade')),
                ('sexo', models.CharField(max_length=255, verbose_name='sexo')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='email')),
                ('senha', models.CharField(max_length=255, null=True, verbose_name='senha')),
            ],
            options={
                'db_table': 'pessoafisica',
                'ordering': ('nome',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField()),
                ('login', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
