# Generated by Django 2.1.2 on 2018-11-19 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'managed': False, 'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='pessoafisica',
            options={'managed': False, 'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False, 'ordering': ('id',)},
        ),
    ]
