# Generated by Django 2.1.2 on 2018-11-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnoLetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='descricao')),
                ('datafinal', models.DateField(verbose_name='datafinal')),
                ('datainicio', models.DateField(verbose_name='datainicio')),
                ('fechadonota', models.BooleanField(verbose_name='fechadonota')),
            ],
            options={
                'db_table': 'anoletivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, null=True, verbose_name='descricao')),
                ('codigo', models.IntegerField(verbose_name='codigo')),
            ],
            options={
                'db_table': 'disciplina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DisciplinaAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargahoraria', models.IntegerField()),
                ('statusdisciplinaaluno', models.CharField(max_length=255)),
                ('matriculaacumulada', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mesesfechadonota', models.IntegerField()),
                ('notaacumulada', models.DecimalField(decimal_places=2, max_digits=5)),
                ('datacadastroprovafinal', models.DateTimeField()),
                ('notaprovafinal', models.DateTimeField()),
                ('fechadoprovafinal', models.BooleanField()),
                ('datacadastroatualizacaoprovafinal', models.DateTimeField()),
                ('notaantigaprovafinal', models.DateTimeField()),
            ],
            options={
                'db_table': 'disciplinaaluno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GradeCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'gradecurso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SerieDisciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'seriedisciplina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SituacaoTurmaMes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datahora', models.DateTimeField()),
                ('status', models.CharField(max_length=255)),
                ('quantidadedeaprovados', models.IntegerField()),
                ('quantidadedereprovados', models.IntegerField()),
            ],
            options={
                'db_table': 'situacaoturmames',
                'managed': False,
            },
        ),
    ]
