# Generated by Django 2.1.5 on 2019-05-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anoletivo',
            options={'managed': False, 'ordering': ('-id',)},
        ),
    ]
