# Generated by Django 2.1.2 on 2018-11-19 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anoletivo',
            options={'managed': False, 'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='disciplinaaluno',
            options={'managed': False, 'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='gradecurso',
            options={'managed': False, 'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='seriedisciplina',
            options={'managed': False, 'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='situacaoturmames',
            options={'managed': False, 'ordering': ('id',)},
        ),
    ]
