# Generated by Django 2.1.4 on 2018-12-27 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0002_auto_20181119_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplina',
            options={'managed': False, 'ordering': ('id',)},
        ),
    ]
