# Generated by Django 2.1.2 on 2018-11-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoNotaMes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sequencia', models.IntegerField()),
                ('inseridofechamento', models.BooleanField()),
                ('tipolancamentonota', models.CharField(max_length=255)),
                ('datahora', models.DateTimeField()),
            ],
            options={
                'db_table': 'alunonotames',
                'managed': False,
            },
        ),
    ]
