# Generated by Django 2.1.5 on 2019-01-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoNotaMes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sequencia', models.IntegerField(null=True)),
                ('inseridofechamento', models.BooleanField(default=False)),
                ('tipolancamentonota', models.CharField(max_length=255)),
                ('datahora', models.DateTimeField()),
            ],
            options={
                'db_table': 'alunonotames',
                'ordering': ('id',),
                'managed': False,
            },
        ),
    ]
