# Generated by Django 2.1.1 on 2018-09-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=255, verbose_name='cpf')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('nacionalidade', models.CharField(max_length=255, verbose_name='nacionalidade')),
                ('sexo', models.CharField(max_length=255, verbose_name='sexo')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='email')),
            ],
            options={
                'db_table': 'pessoafisica',
                'ordering': ('nome',),
                'managed': False,
            },
        ),
    ]
