# Generated by Django 2.1.1 on 2018-09-21 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.IntegerField(verbose_name='cargo')),
                ('pessoafisica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionario.PessoaFisica')),
            ],
        ),
    ]
