# Generated by Django 2.1.1 on 2018-09-21 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_funcionario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'managed': False},
        ),
    ]
