# Generated by Django 2.1.1 on 2018-09-21 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0003_auto_20180921_1107'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='funcionario',
            table='funcionario',
        ),
    ]
