# Generated by Django 2.1.1 on 2018-09-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0005_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionarioEscola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(verbose_name='ativo')),
            ],
            options={
                'db_table': 'funcionarioescola',
                'managed': False,
            },
        ),
    ]
