# Generated by Django 2.1.1 on 2018-09-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0006_funcionarioescola'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, null=True, verbose_name='descricao')),
                ('codigo', models.IntegerField(verbose_name='codigo')),
            ],
            options={
                'db_table': 'disciplina',
                'managed': False,
            },
        ),
    ]
