# Generated by Django 2.1.1 on 2018-10-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0007_disciplina'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'gradecurso',
                'managed': False,
            },
        ),
    ]
