# Generated by Django 2.1.2 on 2018-11-19 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0008_gradecurso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'managed': False, 'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'managed': False, 'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='funcionarioescola',
            options={'managed': False, 'ordering': ('id',)},
        ),
    ]
