# Generated by Django 2.1.5 on 2019-01-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datahora', models.DateTimeField()),
                ('datahoracadastro', models.DateTimeField()),
                ('descricao', models.CharField(max_length=255, null=True)),
                ('enviadosms', models.BooleanField()),
                ('dataenviosms', models.DateTimeField(null=True)),
                ('resumosms', models.CharField(max_length=255, null=True)),
                ('observacao', models.CharField(max_length=255, null=True)),
                ('numerotelefone', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'ocorrencia',
                'ordering': ('id',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoOcorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.BooleanField()),
                ('funcionario', models.BooleanField()),
                ('enviasms', models.BooleanField()),
                ('descricao', models.CharField(max_length=255)),
                ('codigo', models.IntegerField()),
            ],
            options={
                'db_table': 'tipoocorrencia',
                'ordering': ('id',),
                'managed': False,
            },
        ),
    ]
