# Generated by Django 2.1.2 on 2018-10-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datacadastro', models.DateField()),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ocorrencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoOcorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('codigo', models.IntegerField()),
            ],
            options={
                'db_table': 'tipoocorrencia',
                'managed': False,
            },
        ),
    ]
