# Generated by Django 2.1.4 on 2018-12-27 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocorrencia',
            options={'managed': False, 'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='tipoocorrencia',
            options={'managed': False, 'ordering': ('id',)},
        ),
    ]
