# Generated by Django 2.1.1 on 2018-09-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abreviacao', models.CharField(max_length=255, verbose_name='abreviacao')),
                ('cnpj', models.CharField(max_length=255, verbose_name='cnpj')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
            ],
            options={
                'db_table': 'unidade',
                'managed': False,
            },
        ),
    ]
