# Generated by Django 2.1.1 on 2018-09-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalEscola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='descricao')),
            ],
            options={
                'db_table': 'unidadeserie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='descricao')),
                ('nivel', models.CharField(max_length=255, verbose_name='nivel')),
            ],
            options={
                'db_table': 'serie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SerieDisciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'seriedisciplina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='descricao')),
                ('turno', models.CharField(max_length=255, verbose_name='turno')),
                ('nivel', models.CharField(max_length=255, verbose_name='nivel')),
            ],
            options={
                'db_table': 'turma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnoLetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='descricao')),
                ('datafinal', models.DateField(verbose_name='datafinal')),
                ('datainicio', models.DateField(verbose_name='datainicio')),
                ('fechadonota', models.BooleanField(verbose_name='fechadonota')),
            ],
        ),
    ]
