# Generated by Django 2.0 on 2019-07-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechamentoUnidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataalteracao', models.DateTimeField()),
                ('datacadastro', models.DateTimeField()),
            ],
            options={
                'db_table': 'fechamentounidade',
                'ordering': ('id',),
                'managed': False,
            },
        ),
    ]
