# Generated by Django 2.1.1 on 2018-09-24 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unidade', '0002_anoletivo_localescola_serie_seriedisciplina_turma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anoletivo',
            options={'managed': False},
        ),
    ]
