# Generated by Django 2.1.2 on 2018-11-19 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unidade', '0004_auto_20180924_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localescola',
            options={'managed': False, 'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='serie',
            options={'managed': False, 'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'managed': False, 'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='unidade',
            options={'managed': False, 'ordering': ('id',)},
        ),
    ]
